# Generated by Django 6.0.6 on 2026-06-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Received', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=30, unique=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_surname', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('corruption_type', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.officer'),
        ),
        migrations.AddField(
            model_name='case',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.report'),
        ),
    ]
