# Generated by Django 6.0.6 on 2026-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='custom_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
