# Generated by Django 6.0.6 on 2026-07-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_custom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('referral', 'Referral'), ('closed', 'Closed')], default='Received', max_length=30),
        ),
    ]
