# Generated by Django 6.0.6 on 2026-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='position',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='officer_id',
            field=models.CharField(default='OFF001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='institution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('investigation', 'Under Investigation'), ('referral', 'Referral'), ('closed', 'Closed')], default='Received', max_length=30),
        ),
        migrations.AlterField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='officer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='age_group',
            field=models.CharField(choices=[('undere_18', 'Uunder 18'), ('18_24', '18 - 24'), ('25_34', '25 - 34'), ('35_44', '35 - 44'), ('45_54', '45 - 54'), ('55_64', '55 - 64'), ('above_65+', 'Above 65+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='corruption_type',
            field=models.CharField(blank=True, choices=[('bribery', 'Bribery'), ('fraud', 'Fraud'), ('embezzlement', 'Misappropriation of Funds'), ('conflict_interest', 'Conflict of Interest'), ('procurement', 'Procurement Irregularity'), ('abuse_power', 'Abuse of Power'), ('extortion', 'Extortion'), ('other', 'Other Corruption Issue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(choices=[('hhohho', 'Hhohho'), ('manzini', 'Manzini'), ('shiselweni', 'Shiselweni'), ('lubombo', 'Lubombo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.CharField(blank=True, choices=[('public', 'Public Institution'), ('private', 'Private Institution')], max_length=20),
        ),
    ]
