# Generated by Django 6.0.6 on 2026-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_full_name_officer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='age_group',
            field=models.CharField(choices=[('under_18', 'Under 18'), ('18_24', '18 - 24'), ('25_34', '25 - 34'), ('35_44', '35 - 44'), ('45_54', '45 - 54'), ('55_64', '55 - 64'), ('above_65+', 'Above 65+')], max_length=20),
        ),
    ]
