# Generated by Django 6.0.6 on 2026-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=20, unique=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('age_group', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('sector', models.CharField(blank=True, max_length=20, null=True)),
                ('corruption_type', models.CharField(blank=True, choices=[('bribery', 'Bribery'), ('fraud', 'Fraud'), ('abuse', 'Abuse of Power'), ('embezzlement', 'Embezzlement'), ('other', 'Other')], max_length=30, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('pending', 'Pending'), ('closed', 'Closed')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
