# Generated by Django 6.0.6 on 2026-07-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('referral', 'Referral'), ('closed', 'Closed')], default='received', max_length=20),
        ),
    ]
