# Generated by Django 6.0.6 on 2026-07-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auditlog_casestatushistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='casestatushistory',
            name='status',
        ),
        migrations.AddField(
    model_name='auditlog',
    name='case',
    field=models.ForeignKey(
        null=True,
        blank=True,
        on_delete=django.db.models.deletion.CASCADE,
        to='dashboard.case'
    ),
),
        
migrations.AddField(
            model_name='casestatushistory',
            name='new_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
migrations.AddField(
            model_name='casestatushistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='corruption_type',
            field=models.CharField(blank=True, choices=[('bribery', 'Bribery'), ('fraud', 'Fraud'), ('embezzlement', 'Misappropriation of Funds'), ('conflict_interest', 'Conflict of Interest'), ('procurement', 'Procurement Irregularity'), ('abuse_power', 'Abuse of Power'), ('extortion', 'Extortion'), ('other', 'Other Corruption Issue')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='sector',
            field=models.CharField(blank=True, choices=[('public', 'Public Institution'), ('private', 'Private Institution')], max_length=20, null=True),
        ),
    ]
