# Generated by Django 6.0.6 on 2026-07-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_casestatushistory_changed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='corruption_type',
        ),
        migrations.AddField(
            model_name='case',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='age_group',
            field=models.CharField(choices=[('below18', 'Below 18'), ('18_30', '18 - 30'), ('31_45', '31 - 45'), ('46_60', '46 - 60'), ('above60', 'Above 60')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(choices=[('hhohho', 'Hhohho'), ('manzini', 'Manzini'), ('shiselweni', 'Shiselweni'), ('lubombo', 'Lubombo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.case'),
        ),
    ]
