# Generated by Django 6.0.6 on 2026-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_case_corruption_type_case_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='age_group',
            field=models.CharField(choices=[('under18', 'Under 18'), ('18_24', '18 - 24'), ('25_34', '25 - 34'), ('35_44', '35 - 44'), ('45_54', '45 - 54'), ('55_64', '55 - 54'), ('65+', '65+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='sector',
            field=models.CharField(blank=True, choices=[('public', 'Public Sector'), ('private', 'Private Sector')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('investigation', 'Under Investigation'), ('referral', 'Referral'), ('closed', 'Closed')], default='received', max_length=20),
        ),
    ]
