# Generated by Django 6.0.6 on 2026-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_case_age_group_alter_case_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='referral_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
