# Generated by Django 6.0.6 on 2026-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
