# Generated by Django 6.0.6 on 2026-07-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_notification_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reminder_sent',
        ),
    ]
