# Generated by Django 6.0.6 on 2026-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auditlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='case_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
