# Generated by Django 6.0.6 on 2026-07-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auditlog_case_code_auditlog_ip_address_auditlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
    ]
