# Generated by Django 6.0.6 on 2026-07-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_auditlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='case_code',
        ),
    ]
