# Generated by Django 6.0.6 on 2026-07-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_auditlog_case_auditlog_case_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.case'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='case_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
