# Generated by Django 6.0.6 on 2026-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_auditlog_case_code_remove_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='case',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='case_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
