# Generated by Django 6.0.6 on 2026-07-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auditlog_case_auditlog_user_alter_auditlog_case_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='case_code',
        ),
    ]
