# Generated by Django 6.0.6 on 2026-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='case_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
