# Generated by Django 6.0.6 on 2026-07-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auditlog_case_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='case_code',
        ),
    ]
