# Generated by Django 6.0.6 on 2026-07-22 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auditlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='case',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(default='System Notification', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
