# Generated by Django 6.0.6 on 2026-07-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_report_age_group'),
        ('dashboard', '0027_remove_auditlog_action_remove_auditlog_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case'),
        ),
    ]
