# Generated by Django 6.0.6 on 2026-07-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_restore_auditlog_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='case',
        ),
    ]
