# Generated by Django 6.0.6 on 2026-07-23 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_auditlog_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='case',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(default='Unknown Action', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.case'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
