# Generated by Django 6.0.6 on 2026-07-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_notification_action_remove_notification_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default='Anti-Corruption Commission', max_length=150)),
                ('system_name', models.CharField(default='ACC Management System', max_length=150)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisation/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
