# Generated by Django 6.0.6 on 2026-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_organisationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationsettings',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='organisationsettings',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='organisationsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='organisationsettings',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organisationsettings',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisationsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
