# Generated by Django 6.0.6 on 2026-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_organisationsettings_organisation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_custom_statuses', models.BooleanField(default=False)),
                ('automatic_case_numbering', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
