# Generated by Django 6.0.6 on 2026-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_casemanagementsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sector',
            field=models.CharField(blank=True, choices=[('public', 'Public Sector'), ('private', 'Private Sector'), ('none', 'None')], default='none', max_length=20, null=True),
        ),
    ]
