# Generated by Django 6.0.6 on 2026-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_case_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('investigation', 'Under Investigation'), ('referral', 'Referral'), ('closed', 'Closed'), ('declined', 'Declined')], default='received', max_length=20),
        ),
    ]
