# Generated by Django 6.0.6 on 2026-07-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_case_decline_reason_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
