# Generated by Django 6.0.6 on 2026-07-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_anonymousaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='dashboard.anonymousaccount'),
        ),
    ]
